export enum ValidateNewArticleError {
    NO_DATA = 'NO_DATA',
    SERVER_ERROR = 'SERVER_ERROR',
    INCORRECT_TITLE = 'INCORRECT_TITLE',
    INCORRECT_SUBTITLE = 'INCORRECT_SUBTITLE',
    INCORRECT_IMG_URL = 'INCORRECT_IMG_URL',
    INCORRECT_NEW_BLOCKS_LENGTH = 'INCORRECT_NEW_BLOCKS_LENGTH',
    INCORRECT_NEW_TEXT_BLOCK = 'INCORRECT_NEW_TEXT_BLOCK',
    INCORRECT_NEW_CODE_BLOCK = 'INCORRECT_NEW_CODE_BLOCK',
    INCORRECT_NEW_IMAGE_BLOCK_TITLE = 'INCORRECT_NEW_IMAGE_BLOCK_TITLE',
    INCORRECT_NEW_IMAGE_BLOCK_SRC = 'INCORRECT_NEW_IMAGE_BLOCK_SRC',
}
